name: rustc-pull

on:
  workflow_dispatch:
  schedule:
    # Run at 04:00 UTC every Monday and Thursday
    - cron: '0 4 * * 1,4'
  pull_request:

jobs:
  pull:
    uses: kobzol/josh-sync/.github/workflows/rustc-pull.yml@master
#    with:
#      zulip-stream-id: 1
#      zulip-bot-email: bot@bot.com
    secrets:
      zulip-api-token: FOO
      token: ${{ secrets.GITHUB_TOKEN }}
